/* tslint:disable */
/* eslint-disable */
/**
 * minanamanila-api
 * Minanamanila API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: jat.torres@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
