/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface AddressDto
 */
export interface AddressDto {
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    line1?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    postcode?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    province?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    specialInstructions?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressDto
     */
    village?: string;
}


