/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeliveryDateDto
 */
export interface DeliveryDateDto {
    /**
     * 
     * @type {Date}
     * @memberof DeliveryDateDto
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof DeliveryDateDto
     */
    orderLimit?: number;
}

export function DeliveryDateDtoFromJSON(json: any): DeliveryDateDto {
    return DeliveryDateDtoFromJSONTyped(json, false);
}

export function DeliveryDateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryDateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'orderLimit': !exists(json, 'orderLimit') ? undefined : json['orderLimit'],
    };
}

export function DeliveryDateDtoToJSON(value?: DeliveryDateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'orderLimit': value.orderLimit,
    };
}


