/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeliveryDate
 */
export interface DeliveryDate {
    /**
     * 
     * @type {Date}
     * @memberof DeliveryDate
     */
    date?: Date;
    /**
     * 
     * @type {number}
     * @memberof DeliveryDate
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof DeliveryDate
     */
    orderLimit?: number;
}

export function DeliveryDateFromJSON(json: any): DeliveryDate {
    return DeliveryDateFromJSONTyped(json, false);
}

export function DeliveryDateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryDate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'orderLimit': !exists(json, 'orderLimit') ? undefined : json['orderLimit'],
    };
}

export function DeliveryDateToJSON(value?: DeliveryDate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'id': value.id,
        'orderLimit': value.orderLimit,
    };
}


