/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderUpdateDto
 */
export interface OrderUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateDto
     */
    status: OrderUpdateDtoStatusEnum;
}

export function OrderUpdateDtoFromJSON(json: any): OrderUpdateDto {
    return OrderUpdateDtoFromJSONTyped(json, false);
}

export function OrderUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function OrderUpdateDtoToJSON(value?: OrderUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
    };
}

/**
* @export
* @enum {string}
*/
export enum OrderUpdateDtoStatusEnum {
    REGISTERED = 'REGISTERED',
    COOKING = 'COOKING',
    OTW = 'OTW',
    DELIVERED = 'DELIVERED'
}


