/* tslint:disable */
/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderTracking
 */
export interface OrderTracking {
    /**
     * 
     * @type {Date}
     * @memberof OrderTracking
     */
    dateLastUpdated?: Date;
    /**
     * 
     * @type {number}
     * @memberof OrderTracking
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderTracking
     */
    status?: OrderTrackingStatusEnum;
}

export function OrderTrackingFromJSON(json: any): OrderTracking {
    return OrderTrackingFromJSONTyped(json, false);
}

export function OrderTrackingFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderTracking {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dateLastUpdated': !exists(json, 'dateLastUpdated') ? undefined : (new Date(json['dateLastUpdated'])),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function OrderTrackingToJSON(value?: OrderTracking | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dateLastUpdated': value.dateLastUpdated === undefined ? undefined : (value.dateLastUpdated.toISOString()),
        'id': value.id,
        'status': value.status,
    };
}

/**
* @export
* @enum {string}
*/
export enum OrderTrackingStatusEnum {
    REGISTERED = 'REGISTERED',
    COOKING = 'COOKING',
    OTW = 'OTW',
    DELIVERED = 'DELIVERED'
}


